// ============================================================================
// PDF Export - Generate case summary PDFs
// ============================================================================

import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import type { GrievanceCase } from '../types';

/** Generate HTML for a grievance case summary */
function buildCaseHTML(caseData: GrievanceCase): string {
  const isOverdue = caseData.deadline && new Date(caseData.deadline) < new Date();

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 40px; color: #1a1a2e; }
    h1 { color: #1e3a8a; font-size: 24px; margin-bottom: 4px; }
    .subtitle { color: #6b7280; font-size: 14px; margin-bottom: 24px; }
    .section { margin-bottom: 20px; }
    .section-title { font-size: 16px; font-weight: 600; color: #1e3a8a; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px; margin-bottom: 12px; }
    table { width: 100%; border-collapse: collapse; }
    td { padding: 8px 12px; font-size: 14px; border-bottom: 1px solid #f3f4f6; }
    td:first-child { color: #6b7280; width: 120px; font-weight: 500; }
    .status { display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: 600; }
    .status-active { background: #dbeafe; color: #1e40af; }
    .status-overdue { background: #fee2e2; color: #991b1b; }
    .status-resolved { background: #d1fae5; color: #065f46; }
    .notes { background: #f9fafb; padding: 16px; border-radius: 8px; font-size: 14px; line-height: 1.6; }
    .footer { margin-top: 32px; text-align: center; color: #9ca3af; font-size: 11px; }
  </style>
</head>
<body>
  <h1>Case ${caseData.id}</h1>
  <p class="subtitle">Generated by GroupUp Mobile &bull; ${new Date().toLocaleDateString()}</p>

  <div class="section">
    <div class="section-title">Case Information</div>
    <table>
      <tr><td>Member</td><td>${caseData.memberFirstName} ${caseData.memberLastName}</td></tr>
      <tr><td>Status</td><td><span class="status ${isOverdue ? 'status-overdue' : caseData.status.toLowerCase() === 'resolved' ? 'status-resolved' : 'status-active'}">${caseData.status}</span></td></tr>
      ${caseData.step ? `<tr><td>Step</td><td>${caseData.step}</td></tr>` : ''}
      <tr><td>Category</td><td>${caseData.issueCategory || 'N/A'}</td></tr>
      <tr><td>Priority</td><td>${caseData.priority || 'Normal'}</td></tr>
      <tr><td>Filed</td><td>${caseData.filed ? new Date(caseData.filed).toLocaleDateString() : 'N/A'}</td></tr>
      <tr><td>Deadline</td><td style="color: ${isOverdue ? '#dc2626' : '#1a1a2e'}">${caseData.deadline ? new Date(caseData.deadline).toLocaleDateString() : 'N/A'}${isOverdue ? ' (OVERDUE)' : ''}</td></tr>
      <tr><td>Steward</td><td>${caseData.steward || 'Unassigned'}</td></tr>
      <tr><td>Unit</td><td>${caseData.unit || 'N/A'}</td></tr>
    </table>
  </div>

  ${caseData.notes ? `
  <div class="section">
    <div class="section-title">Notes</div>
    <div class="notes">${caseData.notes.replace(/\n/g, '<br/>')}</div>
  </div>` : ''}

  ${caseData.resolution ? `
  <div class="section">
    <div class="section-title">Resolution</div>
    <div class="notes">${caseData.resolution.replace(/\n/g, '<br/>')}</div>
    ${caseData.dateClosed ? `<p style="color: #6b7280; font-size: 12px;">Closed: ${new Date(caseData.dateClosed).toLocaleDateString()}</p>` : ''}
  </div>` : ''}

  <div class="footer">
    GroupUp &bull; SEIU 509 &bull; Confidential
  </div>
</body>
</html>`;
}

/** Export a case as PDF and open share sheet */
export async function exportCasePDF(caseData: GrievanceCase): Promise<boolean> {
  try {
    const html = buildCaseHTML(caseData);
    const { uri } = await Print.printToFileAsync({ html, base64: false });

    const isAvailable = await Sharing.isAvailableAsync();
    if (isAvailable) {
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: `Case ${caseData.id} Summary`,
        UTI: 'com.adobe.pdf',
      });
      return true;
    }
    return false;
  } catch (error) {
    console.error('PDF export failed:', error);
    return false;
  }
}
